// Code generated by MockGen. DO NOT EDIT.
// Source: share-basket-server/usecase (interfaces: GetPersonalShoppingItemsOutputPort)
//
// Generated by this command:
//
//	mockgen -destination=../test/mock/usecase/get_personal_shopping_items_output.go . GetPersonalShoppingItemsOutputPort
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	usecase "share-basket-server/usecase"

	gomock "go.uber.org/mock/gomock"
)

// MockGetPersonalShoppingItemsOutputPort is a mock of GetPersonalShoppingItemsOutputPort interface.
type MockGetPersonalShoppingItemsOutputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetPersonalShoppingItemsOutputPortMockRecorder
	isgomock struct{}
}

// MockGetPersonalShoppingItemsOutputPortMockRecorder is the mock recorder for MockGetPersonalShoppingItemsOutputPort.
type MockGetPersonalShoppingItemsOutputPortMockRecorder struct {
	mock *MockGetPersonalShoppingItemsOutputPort
}

// NewMockGetPersonalShoppingItemsOutputPort creates a new mock instance.
func NewMockGetPersonalShoppingItemsOutputPort(ctrl *gomock.Controller) *MockGetPersonalShoppingItemsOutputPort {
	mock := &MockGetPersonalShoppingItemsOutputPort{ctrl: ctrl}
	mock.recorder = &MockGetPersonalShoppingItemsOutputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetPersonalShoppingItemsOutputPort) EXPECT() *MockGetPersonalShoppingItemsOutputPortMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockGetPersonalShoppingItemsOutputPort) Render(ctx context.Context, output []usecase.GetPersonalShoppingItemOutput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", ctx, output)
	ret0, _ := ret[0].(error)
	return ret0
}

// Render indicates an expected call of Render.
func (mr *MockGetPersonalShoppingItemsOutputPortMockRecorder) Render(ctx, output any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockGetPersonalShoppingItemsOutputPort)(nil).Render), ctx, output)
}
