// Code generated by MockGen. DO NOT EDIT.
// Source: share-basket-server/usecase (interfaces: GetPersonalShoppingItemsInputPort)
//
// Generated by this command:
//
//	mockgen -destination=../test/mock/usecase/get_personal_shopping_items_input.go . GetPersonalShoppingItemsInputPort
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	usecase "share-basket-server/usecase"

	gomock "go.uber.org/mock/gomock"
)

// MockGetPersonalShoppingItemsInputPort is a mock of GetPersonalShoppingItemsInputPort interface.
type MockGetPersonalShoppingItemsInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetPersonalShoppingItemsInputPortMockRecorder
	isgomock struct{}
}

// MockGetPersonalShoppingItemsInputPortMockRecorder is the mock recorder for MockGetPersonalShoppingItemsInputPort.
type MockGetPersonalShoppingItemsInputPortMockRecorder struct {
	mock *MockGetPersonalShoppingItemsInputPort
}

// NewMockGetPersonalShoppingItemsInputPort creates a new mock instance.
func NewMockGetPersonalShoppingItemsInputPort(ctrl *gomock.Controller) *MockGetPersonalShoppingItemsInputPort {
	mock := &MockGetPersonalShoppingItemsInputPort{ctrl: ctrl}
	mock.recorder = &MockGetPersonalShoppingItemsInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetPersonalShoppingItemsInputPort) EXPECT() *MockGetPersonalShoppingItemsInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetPersonalShoppingItemsInputPort) Execute(ctx context.Context, input usecase.GetPersonalShoppingItemsInput, output usecase.GetPersonalShoppingItemsOutputPort) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input, output)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockGetPersonalShoppingItemsInputPortMockRecorder) Execute(ctx, input, output any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetPersonalShoppingItemsInputPort)(nil).Execute), ctx, input, output)
}
