// Code generated by MockGen. DO NOT EDIT.
// Source: share-basket-server/usecase (interfaces: LoginInputPort)
//
// Generated by this command:
//
//	mockgen -destination=../test/mock/usecase/login_input.go . LoginInputPort
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	usecase "share-basket-server/usecase"

	gomock "go.uber.org/mock/gomock"
)

// MockLoginInputPort is a mock of LoginInputPort interface.
type MockLoginInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockLoginInputPortMockRecorder
	isgomock struct{}
}

// MockLoginInputPortMockRecorder is the mock recorder for MockLoginInputPort.
type MockLoginInputPortMockRecorder struct {
	mock *MockLoginInputPort
}

// NewMockLoginInputPort creates a new mock instance.
func NewMockLoginInputPort(ctrl *gomock.Controller) *MockLoginInputPort {
	mock := &MockLoginInputPort{ctrl: ctrl}
	mock.recorder = &MockLoginInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginInputPort) EXPECT() *MockLoginInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockLoginInputPort) Execute(ctx context.Context, input usecase.LoginInput, output usecase.LoginOutputPort) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input, output)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockLoginInputPortMockRecorder) Execute(ctx, input, output any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockLoginInputPort)(nil).Execute), ctx, input, output)
}
