// Code generated by MockGen. DO NOT EDIT.
// Source: share-basket-server/usecase (interfaces: SignUpInputPort)
//
// Generated by this command:
//
//	mockgen -destination=../test/mock/usecase/signup_input.go . SignUpInputPort
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	usecase "share-basket-server/usecase"

	gomock "go.uber.org/mock/gomock"
)

// MockSignUpInputPort is a mock of SignUpInputPort interface.
type MockSignUpInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSignUpInputPortMockRecorder
	isgomock struct{}
}

// MockSignUpInputPortMockRecorder is the mock recorder for MockSignUpInputPort.
type MockSignUpInputPortMockRecorder struct {
	mock *MockSignUpInputPort
}

// NewMockSignUpInputPort creates a new mock instance.
func NewMockSignUpInputPort(ctrl *gomock.Controller) *MockSignUpInputPort {
	mock := &MockSignUpInputPort{ctrl: ctrl}
	mock.recorder = &MockSignUpInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignUpInputPort) EXPECT() *MockSignUpInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSignUpInputPort) Execute(ctx context.Context, input usecase.SignUpInput, output usecase.SignUpOutputPort) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input, output)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockSignUpInputPortMockRecorder) Execute(ctx, input, output any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSignUpInputPort)(nil).Execute), ctx, input, output)
}
