// Code generated by MockGen. DO NOT EDIT.
// Source: share-basket-server/usecase (interfaces: SignUpConfirmOutputPort)
//
// Generated by this command:
//
//	mockgen -destination=../test/mock/usecase/signup_confirm_output.go . SignUpConfirmOutputPort
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSignUpConfirmOutputPort is a mock of SignUpConfirmOutputPort interface.
type MockSignUpConfirmOutputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSignUpConfirmOutputPortMockRecorder
	isgomock struct{}
}

// MockSignUpConfirmOutputPortMockRecorder is the mock recorder for MockSignUpConfirmOutputPort.
type MockSignUpConfirmOutputPortMockRecorder struct {
	mock *MockSignUpConfirmOutputPort
}

// NewMockSignUpConfirmOutputPort creates a new mock instance.
func NewMockSignUpConfirmOutputPort(ctrl *gomock.Controller) *MockSignUpConfirmOutputPort {
	mock := &MockSignUpConfirmOutputPort{ctrl: ctrl}
	mock.recorder = &MockSignUpConfirmOutputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignUpConfirmOutputPort) EXPECT() *MockSignUpConfirmOutputPortMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockSignUpConfirmOutputPort) Render(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Render indicates an expected call of Render.
func (mr *MockSignUpConfirmOutputPortMockRecorder) Render(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockSignUpConfirmOutputPort)(nil).Render), ctx)
}
