root = "."
testdata_dir = "testdata"
tmp_dir = ".air"

[build]
  bin = ".air/bin/main"
  cmd = "go build -o .air/bin/main ./cmd/api/main.go"
  delay = 1000
  exclude_dir = ["docker", "tmp"]
  exclude_regex = ["_test.go"]
  full_bin = ".air/bin/main"
  include_ext = ["go"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
