services:
  api:
    build:
      context: .
      dockerfile: docker/go/Dockerfile.dev
    container_name: api
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/app
    env_file: .env
    tty: true
    depends_on:
      - db
  db:
    image: postgres:17
    restart: always
    container_name: db
    ports:
      - ${DB_PORT}:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/data
