FROM golang:1.24.2-alpine AS develop

ENV TZ=Asia/Tokyo
ENV GO111MODULE=on

WORKDIR /go/src/app

COPY go.mod go.sum ./

RUN go install github.com/air-verse/air@latest
RUN go install github.com/rubenv/sql-migrate/...@latest
RUN go install go.uber.org/mock/mockgen@latest

RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"]