FROM golang:1.24-alpine AS develop

ENV TZ=Asia/Tokyo
ENV GO111MODULE=on

WORKDIR /go/src/app

COPY go.sum go.mod ./

RUN go install github.com/rubenv/sql-migrate/...@latest
RUN go install go.uber.org/mock/mockgen@latest
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest


CMD ["go", "run", "cmd/grpc/main.go"]