-- +migrate Up
CREATE TABLE IF NOT EXISTS families (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    owner_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_families_owners FOREIGN KEY (owner_id) REFERENCES accounts(id) ON DELETE CASCADE
);

-- +migrate Down
DROP TABLE IF EXISTS familes;