// Code generated by MockGen. DO NOT EDIT.
// Source: share-basket-server/infra/aws (interfaces: CognitoClient)
//
// Generated by this command:
//
//	mockgen -destination=../../mock/aws/cognito_client.go . CognitoClient
//

// Package mock_aws is a generated GoMock package.
package mock_aws

import (
	context "context"
	reflect "reflect"

	cognitoidentityprovider "github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	jwt "github.com/golang-jwt/jwt/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockCognitoClient is a mock of CognitoClient interface.
type MockCognitoClient struct {
	ctrl     *gomock.Controller
	recorder *MockCognitoClientMockRecorder
	isgomock struct{}
}

// MockCognitoClientMockRecorder is the mock recorder for MockCognitoClient.
type MockCognitoClientMockRecorder struct {
	mock *MockCognitoClient
}

// NewMockCognitoClient creates a new mock instance.
func NewMockCognitoClient(ctrl *gomock.Controller) *MockCognitoClient {
	mock := &MockCognitoClient{ctrl: ctrl}
	mock.recorder = &MockCognitoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCognitoClient) EXPECT() *MockCognitoClientMockRecorder {
	return m.recorder
}

// AdminDeleteUser mocks base method.
func (m *MockCognitoClient) AdminDeleteUser(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminDeleteUser", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminDeleteUser indicates an expected call of AdminDeleteUser.
func (mr *MockCognitoClientMockRecorder) AdminDeleteUser(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminDeleteUser", reflect.TypeOf((*MockCognitoClient)(nil).AdminDeleteUser), ctx, email)
}

// ConfirmSignUp mocks base method.
func (m *MockCognitoClient) ConfirmSignUp(ctx context.Context, email, confirmationCode string) (*cognitoidentityprovider.ConfirmSignUpOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmSignUp", ctx, email, confirmationCode)
	ret0, _ := ret[0].(*cognitoidentityprovider.ConfirmSignUpOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmSignUp indicates an expected call of ConfirmSignUp.
func (mr *MockCognitoClientMockRecorder) ConfirmSignUp(ctx, email, confirmationCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmSignUp", reflect.TypeOf((*MockCognitoClient)(nil).ConfirmSignUp), ctx, email, confirmationCode)
}

// InitiateAuth mocks base method.
func (m *MockCognitoClient) InitiateAuth(ctx context.Context, email, password string) (*cognitoidentityprovider.InitiateAuthOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateAuth", ctx, email, password)
	ret0, _ := ret[0].(*cognitoidentityprovider.InitiateAuthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateAuth indicates an expected call of InitiateAuth.
func (mr *MockCognitoClientMockRecorder) InitiateAuth(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateAuth", reflect.TypeOf((*MockCognitoClient)(nil).InitiateAuth), ctx, email, password)
}

// ParseToken mocks base method.
func (m *MockCognitoClient) ParseToken(ctx context.Context, token string) (*jwt.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseToken", ctx, token)
	ret0, _ := ret[0].(*jwt.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseToken indicates an expected call of ParseToken.
func (mr *MockCognitoClientMockRecorder) ParseToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseToken", reflect.TypeOf((*MockCognitoClient)(nil).ParseToken), ctx, token)
}

// SignUp mocks base method.
func (m *MockCognitoClient) SignUp(ctx context.Context, email, password string) (*cognitoidentityprovider.SignUpOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, email, password)
	ret0, _ := ret[0].(*cognitoidentityprovider.SignUpOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignUp indicates an expected call of SignUp.
func (mr *MockCognitoClientMockRecorder) SignUp(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockCognitoClient)(nil).SignUp), ctx, email, password)
}
