// Code generated by MockGen. DO NOT EDIT.
// Source: share-basket-server/domain (interfaces: PersonalShoppingItemRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/domain/personal_shopping_item.go . PersonalShoppingItemRepository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"
	domain "share-basket-server/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockPersonalShoppingItemRepository is a mock of PersonalShoppingItemRepository interface.
type MockPersonalShoppingItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPersonalShoppingItemRepositoryMockRecorder
	isgomock struct{}
}

// MockPersonalShoppingItemRepositoryMockRecorder is the mock recorder for MockPersonalShoppingItemRepository.
type MockPersonalShoppingItemRepositoryMockRecorder struct {
	mock *MockPersonalShoppingItemRepository
}

// NewMockPersonalShoppingItemRepository creates a new mock instance.
func NewMockPersonalShoppingItemRepository(ctrl *gomock.Controller) *MockPersonalShoppingItemRepository {
	mock := &MockPersonalShoppingItemRepository{ctrl: ctrl}
	mock.recorder = &MockPersonalShoppingItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonalShoppingItemRepository) EXPECT() *MockPersonalShoppingItemRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockPersonalShoppingItemRepository) GetAll() ([]domain.PersonalShoppingItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]domain.PersonalShoppingItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPersonalShoppingItemRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPersonalShoppingItemRepository)(nil).GetAll))
}

// Store mocks base method.
func (m *MockPersonalShoppingItemRepository) Store(item *domain.PersonalShoppingItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockPersonalShoppingItemRepositoryMockRecorder) Store(item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockPersonalShoppingItemRepository)(nil).Store), item)
}
