// Code generated by MockGen. DO NOT EDIT.
// Source: share-basket-server/domain (interfaces: ShoppingCategoryRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/domain/shopping_category.go . ShoppingCategoryRepository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"
	domain "share-basket-server/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockShoppingCategoryRepository is a mock of ShoppingCategoryRepository interface.
type MockShoppingCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShoppingCategoryRepositoryMockRecorder
	isgomock struct{}
}

// MockShoppingCategoryRepositoryMockRecorder is the mock recorder for MockShoppingCategoryRepository.
type MockShoppingCategoryRepositoryMockRecorder struct {
	mock *MockShoppingCategoryRepository
}

// NewMockShoppingCategoryRepository creates a new mock instance.
func NewMockShoppingCategoryRepository(ctrl *gomock.Controller) *MockShoppingCategoryRepository {
	mock := &MockShoppingCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockShoppingCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShoppingCategoryRepository) EXPECT() *MockShoppingCategoryRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockShoppingCategoryRepository) GetAll() ([]domain.ShoppingCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]domain.ShoppingCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockShoppingCategoryRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockShoppingCategoryRepository)(nil).GetAll))
}
