// Code generated by MockGen. DO NOT EDIT.
// Source: share-basket-server/usecase (interfaces: GetShoppingCategoriesInputPort)
//
// Generated by this command:
//
//	mockgen -destination=../mock/usecase/get_shopping_categories_input.go . GetShoppingCategoriesInputPort
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	usecase "share-basket-server/usecase"

	gomock "go.uber.org/mock/gomock"
)

// MockGetShoppingCategoriesInputPort is a mock of GetShoppingCategoriesInputPort interface.
type MockGetShoppingCategoriesInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetShoppingCategoriesInputPortMockRecorder
	isgomock struct{}
}

// MockGetShoppingCategoriesInputPortMockRecorder is the mock recorder for MockGetShoppingCategoriesInputPort.
type MockGetShoppingCategoriesInputPortMockRecorder struct {
	mock *MockGetShoppingCategoriesInputPort
}

// NewMockGetShoppingCategoriesInputPort creates a new mock instance.
func NewMockGetShoppingCategoriesInputPort(ctrl *gomock.Controller) *MockGetShoppingCategoriesInputPort {
	mock := &MockGetShoppingCategoriesInputPort{ctrl: ctrl}
	mock.recorder = &MockGetShoppingCategoriesInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetShoppingCategoriesInputPort) EXPECT() *MockGetShoppingCategoriesInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetShoppingCategoriesInputPort) Execute(ctx context.Context, output usecase.GetShoppingCategoriesOutputPort) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, output)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockGetShoppingCategoriesInputPortMockRecorder) Execute(ctx, output any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetShoppingCategoriesInputPort)(nil).Execute), ctx, output)
}
