// Code generated by MockGen. DO NOT EDIT.
// Source: share-basket-server/usecase (interfaces: GetShoppingCategoriesOutputPort)
//
// Generated by this command:
//
//	mockgen -destination=../mock/usecase/get_shopping_categories_output.go . GetShoppingCategoriesOutputPort
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	usecase "share-basket-server/usecase"

	gomock "go.uber.org/mock/gomock"
)

// MockGetShoppingCategoriesOutputPort is a mock of GetShoppingCategoriesOutputPort interface.
type MockGetShoppingCategoriesOutputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetShoppingCategoriesOutputPortMockRecorder
	isgomock struct{}
}

// MockGetShoppingCategoriesOutputPortMockRecorder is the mock recorder for MockGetShoppingCategoriesOutputPort.
type MockGetShoppingCategoriesOutputPortMockRecorder struct {
	mock *MockGetShoppingCategoriesOutputPort
}

// NewMockGetShoppingCategoriesOutputPort creates a new mock instance.
func NewMockGetShoppingCategoriesOutputPort(ctrl *gomock.Controller) *MockGetShoppingCategoriesOutputPort {
	mock := &MockGetShoppingCategoriesOutputPort{ctrl: ctrl}
	mock.recorder = &MockGetShoppingCategoriesOutputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetShoppingCategoriesOutputPort) EXPECT() *MockGetShoppingCategoriesOutputPortMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockGetShoppingCategoriesOutputPort) Render(ctx context.Context, outputs []usecase.GetShoppingCategoryOutput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", ctx, outputs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Render indicates an expected call of Render.
func (mr *MockGetShoppingCategoriesOutputPortMockRecorder) Render(ctx, outputs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockGetShoppingCategoriesOutputPort)(nil).Render), ctx, outputs)
}
