// Code generated by MockGen. DO NOT EDIT.
// Source: share-basket-server/usecase (interfaces: LoginOutputPort)
//
// Generated by this command:
//
//	mockgen -destination=../mock/usecase/login_output.go . LoginOutputPort
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLoginOutputPort is a mock of LoginOutputPort interface.
type MockLoginOutputPort struct {
	ctrl     *gomock.Controller
	recorder *MockLoginOutputPortMockRecorder
	isgomock struct{}
}

// MockLoginOutputPortMockRecorder is the mock recorder for MockLoginOutputPort.
type MockLoginOutputPortMockRecorder struct {
	mock *MockLoginOutputPort
}

// NewMockLoginOutputPort creates a new mock instance.
func NewMockLoginOutputPort(ctrl *gomock.Controller) *MockLoginOutputPort {
	mock := &MockLoginOutputPort{ctrl: ctrl}
	mock.recorder = &MockLoginOutputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginOutputPort) EXPECT() *MockLoginOutputPortMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockLoginOutputPort) Render(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Render indicates an expected call of Render.
func (mr *MockLoginOutputPortMockRecorder) Render(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockLoginOutputPort)(nil).Render), ctx, token)
}
