// Code generated by MockGen. DO NOT EDIT.
// Source: share-basket-server/usecase (interfaces: SignUpOutputPort)
//
// Generated by this command:
//
//	mockgen -destination=../mock/usecase/signup_output.go . SignUpOutputPort
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSignUpOutputPort is a mock of SignUpOutputPort interface.
type MockSignUpOutputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSignUpOutputPortMockRecorder
	isgomock struct{}
}

// MockSignUpOutputPortMockRecorder is the mock recorder for MockSignUpOutputPort.
type MockSignUpOutputPortMockRecorder struct {
	mock *MockSignUpOutputPort
}

// NewMockSignUpOutputPort creates a new mock instance.
func NewMockSignUpOutputPort(ctrl *gomock.Controller) *MockSignUpOutputPort {
	mock := &MockSignUpOutputPort{ctrl: ctrl}
	mock.recorder = &MockSignUpOutputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignUpOutputPort) EXPECT() *MockSignUpOutputPortMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockSignUpOutputPort) Render(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Render indicates an expected call of Render.
func (mr *MockSignUpOutputPortMockRecorder) Render(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockSignUpOutputPort)(nil).Render), ctx)
}
