// Code generated by MockGen. DO NOT EDIT.
// Source: share-basket-server/usecase (interfaces: SignUpConfirmInputPort)
//
// Generated by this command:
//
//	mockgen -destination=../mock/usecase/signup_confirm_input.go . SignUpConfirmInputPort
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	usecase "share-basket-server/usecase"

	gomock "go.uber.org/mock/gomock"
)

// MockSignUpConfirmInputPort is a mock of SignUpConfirmInputPort interface.
type MockSignUpConfirmInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSignUpConfirmInputPortMockRecorder
	isgomock struct{}
}

// MockSignUpConfirmInputPortMockRecorder is the mock recorder for MockSignUpConfirmInputPort.
type MockSignUpConfirmInputPortMockRecorder struct {
	mock *MockSignUpConfirmInputPort
}

// NewMockSignUpConfirmInputPort creates a new mock instance.
func NewMockSignUpConfirmInputPort(ctrl *gomock.Controller) *MockSignUpConfirmInputPort {
	mock := &MockSignUpConfirmInputPort{ctrl: ctrl}
	mock.recorder = &MockSignUpConfirmInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignUpConfirmInputPort) EXPECT() *MockSignUpConfirmInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSignUpConfirmInputPort) Execute(ctx context.Context, input usecase.SignUpConfirmInput, output usecase.SignUpConfirmOutputPort) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input, output)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockSignUpConfirmInputPortMockRecorder) Execute(ctx, input, output any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSignUpConfirmInputPort)(nil).Execute), ctx, input, output)
}
