// Code generated by MockGen. DO NOT EDIT.
// Source: share-basket-server/usecase (interfaces: VerifyTokenInputPort)
//
// Generated by this command:
//
//	mockgen -destination=../mock/usecase/verify_token_input.go . VerifyTokenInputPort
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVerifyTokenInputPort is a mock of VerifyTokenInputPort interface.
type MockVerifyTokenInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyTokenInputPortMockRecorder
	isgomock struct{}
}

// MockVerifyTokenInputPortMockRecorder is the mock recorder for MockVerifyTokenInputPort.
type MockVerifyTokenInputPortMockRecorder struct {
	mock *MockVerifyTokenInputPort
}

// NewMockVerifyTokenInputPort creates a new mock instance.
func NewMockVerifyTokenInputPort(ctrl *gomock.Controller) *MockVerifyTokenInputPort {
	mock := &MockVerifyTokenInputPort{ctrl: ctrl}
	mock.recorder = &MockVerifyTokenInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyTokenInputPort) EXPECT() *MockVerifyTokenInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockVerifyTokenInputPort) Execute(ctx context.Context, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockVerifyTokenInputPortMockRecorder) Execute(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockVerifyTokenInputPort)(nil).Execute), ctx, token)
}
