name: BFF Test
on:
  push:
    branches:
      - main
    paths:
      - 'bff/**'
  pull_request:
    paths:
      - 'bff/**'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'bff/.node-version'

      - name: Install dependencies
        run: npm ci
        working-directory: bff

      - name: Run tests
        run: npm test
        working-directory: bff


