name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      DB_PORT: 5432
      TEST_DB_HOST: localhost
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      
      - name: Install dependencies
        run: go mod download
      - name: Run test
        run: go test -v -covermode=count ./...
