name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      
      - name: Install dependencies
        run: go mod download
      - name: Run test
        run: go test -v -covermode=count ./...
